FROM node:lts-alpine as build-stage
WORKDIR /journey-planner
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /journey-planner
COPY --from=build-stage /journey-planner/dist /journey-planner
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80